### ISSUE TITLE
Geodata outdated

### ISSUE THREAD

**Issue by ThorbenJensen** [codeformuenster/containermap#6]
The geojson file in the repository (extracted from OpenStreetMap) is outdated.

For the difference between the data in the repository and the most recent OpenStreetMap data,
please find attached a screenshot. 

![screenshot from 2016-05-04 21 52 45](https://cloud.githubusercontent.com/assets/6625253/15027162/920bfc2e-1242-11e6-8b80-1667e6bfed13.png)

**Comment by ubergesundheit** [comment]
Feel free to create a pull request! ;)
